services:
  - type: web
    name: smart-seg-model
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port 10000 --server.address 0.0.0.0"
    plan: free
    envVars: {}
